export enum FormEvents {
  UPDATE = 'UPDATE',
  RESET = 'RESET',
  UPDATE_ITEM = 'UPDATE_ITEM',
  UPDATE_CONTROL_ITEMS = 'UPDATE_CONTROL_ITEMS',
  UPDATE_REGISTER_ITEMS = 'UPDATE_REGISTER_ITEMS',
  UPDATE_PROPERTY_VALUE = 'UPDATE_PROPERTY_VALUE',
  DATA_READING_STARTED = 'DATA_READING_STARTED',
  DATA_READING_ENDED = 'DATA_READING_ENDED'
}
