export enum FormEvents {
  UPDATE = 'UPDATE',
  RESET = 'RESET',
  START = 'START',
  REGISTER_ITEMS = 'REGISTER_ITEMS',
  UPDATE_ITEM = 'UPDATE_ITEM',
  UPDATE_CONTROL_ITEMS = 'UPDATE_CONTROL_ITEMS',
  UPDATE_PROPERTY_VALUE = 'UPDATE_PROPERTY_VALUE'
}
